-- MySQL Script generated by MySQL Workbench
-- qua 11 abr 2018 11:24:25 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema desafio2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `desafio2` ;

-- -----------------------------------------------------
-- Schema desafio2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `desafio2` DEFAULT CHARACTER SET utf8 ;
USE `desafio2` ;

-- -----------------------------------------------------
-- Table `desafio2`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio2`.`company` ;

CREATE TABLE IF NOT EXISTS `desafio2`.`company` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio2`.`condom`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio2`.`condom` ;

CREATE TABLE IF NOT EXISTS `desafio2`.`condom` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `company_id` INT NOT NULL,
  PRIMARY KEY (`id`, `company_id`),
  INDEX `fk_condom_company_idx` (`company_id` ASC),
  CONSTRAINT `fk_condom_company`
    FOREIGN KEY (`company_id`)
    REFERENCES `desafio2`.`company` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio2`.`allotment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio2`.`allotment` ;

CREATE TABLE IF NOT EXISTS `desafio2`.`allotment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `condom_id` INT NOT NULL,
  PRIMARY KEY (`id`, `condom_id`),
  INDEX `fk_Lote_condom1_idx` (`condom_id` ASC),
  CONSTRAINT `fk_Lote_condom1`
    FOREIGN KEY (`condom_id`)
    REFERENCES `desafio2`.`condom` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `desafio2`.`dweller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `desafio2`.`dweller` ;

CREATE TABLE IF NOT EXISTS `desafio2`.`dweller` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `allotment_id` INT NOT NULL,
  PRIMARY KEY (`id`, `allotment_id`),
  INDEX `fk_dweller_allotment1_idx` (`allotment_id` ASC),
  CONSTRAINT `fk_dweller_allotment1`
    FOREIGN KEY (`allotment_id`)
    REFERENCES `desafio2`.`allotment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
