<head>
		<meta charset="utf-8">
		<title> Empresas </title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
	</head>
	<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
	  <a class="navbar-brand" href="#">Menu</a>
	  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
	    <span class="navbar-toggler-icon"></span>
	  </button>

	  <div class="collapse navbar-collapse" id="navbarSupportedContent">
	    <ul class="navbar-nav mr-auto">
	      <li class="nav-item active">
	        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="../company/index.php">Empresas</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="../allotment/index.php">Lotes</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="../condom/index.php">Condomínios</a>
	      </li>
	      <li class="nav-item">
	        <a class="nav-link" href="../dweller/index.php">Moradores</a>
	      </li>
	    </ul>
	  </div>
	</nav>